[zh-cn]
  title = "MtF.wiki"
  languageName = "简体中文"
  weight = 1
  contentDir = "content/zh-cn"
  currency = "CNY"

[zh-hant]
  title = "MtF.wiki"
  languageName = "繁體中文"
  weight = 2
  contentDir = "content/zh-hant"
  currency = "TWD"

[en]
  title = "ZDoc"
  languageName = "English"
  weight = 1
  contentdir = "content/en"
