name: Deploy Aboutrans to Pages

on:
  push:
    paths-ignore:
      - "images/**"
      - "LICENSE"
      - "README.md"
    branches:
      - master
      - exampleSite
  workflow_dispatch:
    # manual run
    inputs:
      hugoVersion:
        description: "Hugo Version"
        required: false
        default: "0.115.4"

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build-aboutrans:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.115.4"
    steps:
      - name: Add SSH key
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.SECRET_REPO_DEPLOY_KEY }}'
    - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Generated Cache
        uses: actions/cache@v3
        with:
          path: resources/_gen
          key: ${{ runner.os }}-generated-${{ hashFiles('**') }}
          restore-keys: ${{ runner.os }}-generated
      - name: Get Theme
        run: git submodule update --init --recursive
        run: git submodule update --remote --merge
      - name: Build
        run: hugo --minify --enableGitInfo
      - name: Upload artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
  # Deployment job
  deploy-aboutrans:
    needs: build-aboutrans
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
